# docs: https://starship.rs/config/
# explain what is displayed: $ starship explain
# pure prompt

format = """
$username\
$hostname\
$directory\
$nix_shell \
$python\
$kubernetes\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "blue"
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[â¯](purple)"
error_symbol = "[â¯](red)"
vicmd_symbol = "[â®](green)"

[git_branch]
format = "${symbol} [$branch]($style) "
style = "bright-black"
symbol = "ğŸŒ±"

[git_status]
# See https://starship.rs/config/#git-status
format = '([$all_status$ahead_behind]($style) ) '

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"
cherry_pick = "[ğŸ’ PICKING](bold red)"


[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[ ${symbol} $virtualenv]($style) "
style = "bright-black"
symbol = "ğŸ"

[nix_shell]
# disabled = true
impure_msg = 'ğŸ§ª'
pure_msg = 'âœ¨'
unknown_msg = '[unknown shell](bold yellow)'
format = '[$symbol $state $name](bold blue) '
symbol = "â„ï¸"

[kubernetes]
disabled = false
format = '[${symbol} $context( \($namespace\))]($style) '
symbol = "â›µï¸"
